id: P009303
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21848
  title: བུ་སྟོན་གྱི་སྐར་རྩིས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    f51afbc89f2141c995f68af2b9b88e6d:
      image_group_id: I1KG12340
      title: ''
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
